config/routes.rb
Fanfic::Application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comentarios
  end
  root :to => "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comentarios
  validates :titulo, :presence => true
  validates :conteudo, :presence => true, :length => { :minimum => 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def autenticacao
    authenticate_or_request_with_http_basic do |usuario, senha|
      usuario == 'admin' && senha == 'yourfanfic'
    end
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  #before_filter :autenticacao, :only => [:destroy]
  def create
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.create(com_params)
    redirect_to post_path(@post)
   end
   def destroy
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to post_path(@post)
  end
  def com_params
    params.require(:comentario).permit(:autor, :conteudo)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_filter :autenticacao, :except => [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :conteudo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor %>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Conteudo</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.post_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
       </tr>
     <% end %>
    </tbody>
    </table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Comentario', new_comentario_path %>
<% end %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p>
  <strong>Autor:</strong>
  <%= @comentario.autor %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comentario.post_id %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>

    <title>Fanfic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    </head>

<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/index.html">YourFanfic</a>
    </div>
    <ul class="nav navbar-nav">
    <%# <li><%= link_to "Home", home_path %></li>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logado como: <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Conteudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.conteudo %></td>
        <td><%= link_to 'Show', post %></td>
         <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
       </tr>
     <% end %>
   </tbody>
 </table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= simple_format(@post.conteudo) %>

</p>

<h2>Comentarios</h2>
<% @post.comentarios.each do |comentario| %>
  <p>
    <b>Autor:</b>
    <%= comentario.autor %>
  </p>

  <p>
    <b>Comentario:</b>
    <%= comentario.conteudo %>
  </p>
<hr />
<% end %>

<h2>Adicione um comentario:</h2>
<%= form_for([@post, @post.comentarios.build]) do |f| %>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>


<br />

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>